name: Build & Deploy

on:
  push:
    tags:
      - "v*"

env:
  DOCKER_LOGIN: simple2b
  IMAGE_BACK: simple2b/cats
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  STAGING_FOLDER: "~/paris"

jobs:
  build:
    runs-on: Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_LOGIN }}
          password: ${{ env.DOCKER_ACCESS_TOKEN }}
      - name: Build and Push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE_BACK }}:latest
